### ISSUE TITLE
Div by zero when doing cpCircleShapePointQuery()

### ISSUE THREAD

**Issue by stolk** [slembcke/Chipmunk2D#165]
If you query for shapes near point, and there is a circle at the exact same point, a division by zero occurs.

```
>>> where
#0  0x000000000045e003 in cpCircleShapePointQuery (circle=0xf54090, p=..., info=0x7fffffffd080) at /home/bram/src/Chipmunk2D/src/cpShape.c:306
#1  0x000000000045d7a5 in cpShapePointQuery (shape=0xf54090, p=..., info=0x7fffffffd080) at /home/bram/src/Chipmunk2D/src/cpShape.c:232
#2  0x0000000000464e35 in NearestPointQuery (context=0x7fffffffd320, shape=0xf54090, id=0, data=0x0) at /home/bram/src/Chipmunk2D/src/cpSpaceQuery.c:40
#3  0x0000000000468e2a in SubtreeQuery (subtree=0xf1dac0, obj=0x7fffffffd320, bb=..., func=0x464db6 <NearestPointQuery>, data=0x0) at /home/bram/src/Chipmunk2D/src/cpBBTree.c:357
#4  0x0000000000468e54 in SubtreeQuery (subtree=0xf1da80, obj=0x7fffffffd320, bb=..., func=0x464db6 <NearestPointQuery>, data=0x0) at /home/bram/src/Chipmunk2D/src/cpBBTree.c:359
#5  0x0000000000468e54 in SubtreeQuery (subtree=0xf1db80, obj=0x7fffffffd320, bb=..., func=0x464db6 <NearestPointQuery>, data=0x0) at /home/bram/src/Chipmunk2D/src/cpBBTree.c:359
#6  0x0000000000468e80 in SubtreeQuery (subtree=0xf1db00, obj=0x7fffffffd320, bb=..., func=0x464db6 <NearestPointQuery>, data=0x0) at /home/bram/src/Chipmunk2D/src/cpBBTree.c:360
#7  0x0000000000469ee0 in cpBBTreeQuery (tree=0xee7250, obj=0x7fffffffd320, bb=..., func=0x464db6 <NearestPointQuery>, data=0x0) at /home/bram/src/Chipmunk2D/src/cpBBTree.c:684
#8  0x0000000000464ca3 in cpSpatialIndexQuery (index=0xee7250, obj=0x7fffffffd320, bb=..., func=0x464db6 <NearestPointQuery>, data=0x0) at /home/bram/src/Chipmunk2D/include/chipmunk/cpSpatialIndex.h:210
#9  0x0000000000464fd3 in cpSpacePointQuery (space=0xee7010, point=..., maxDistance=0.80000001192092896, filter=..., func=0x40dec0 <queryfunc(cpShape*, cpVect, double, cpVect, void*)>, data=0x0) at /home/bram/src/Chipmunk2D/src/cpSpaceQuery.c:55
```

**Comment by stolk** [comment]
FIxed and merged.
